package brain

// const CONNECTION_STRENGTH_MUTATE_PROBABILITY = 0.01
// const CONNECTION_STRENGTH_MUTATION_SCOPE = 0.001

// const NODE_WEIGHT_MUTATE_PROBABILITY = 0.05
// const NODE_BIAS_MUTATE_PROBABILITY = 0.01
// const NODE_WEIGHT_MUTATION_SCOPE = 0.01
// const NODE_BIAS_MUTATION_SCOPE = 0.01

// const CONNECTION_SPLIT_PROBABILITY = 0.0001
// const MUTATION_PROBABILITY = 0.5

// const NEW_CONNECTION_PROBABILITY = 0.0001

type Config struct {
	CONNECTION_STRENGTH_MUTATE_PROBABILITY float64 `json:"CONNECTION_STRENGTH_MUTATE_PROBABILITY"`
	CONNECTION_STRENGTH_MUTATION_SCOPE     float64 `json:"CONNECTION_STRENGTH_MUTATION_SCOPE"`

	NODE_WEIGHT_MUTATE_PROBABILITY float64 `json:"NODE_WEIGHT_MUTATE_PROBABILITY"`
	NODE_BIAS_MUTATE_PROBABILITY   float64 `json:"NODE_BIAS_MUTATE_PROBABILITY"`
	NODE_WEIGHT_MUTATION_SCOPE     float64 `json:"NODE_WEIGHT_MUTATION_SCOPE"`
	NODE_BIAS_MUTATION_SCOPE       float64 `json:"NODE_BIAS_MUTATION_SCOPE"`

	CONNECTION_SPLIT_PROBABILITY float64 `json:"CONNECTION_SPLIT_PROBABILITY"`
	MUTATION_PROBABILITY         float64 `json:"MUTATION_PROBABILITY"`

	NEW_CONNECTION_PROBABILITY float64 `json:"NEW_CONNECTION_PROBABILITY"`
}

func LoadDefaultConfig() *Config {
	return &Config{
		CONNECTION_STRENGTH_MUTATE_PROBABILITY: 0.01,
		CONNECTION_STRENGTH_MUTATION_SCOPE:     0.001,

		NODE_WEIGHT_MUTATE_PROBABILITY: 0.05,
		NODE_BIAS_MUTATE_PROBABILITY:   0.01,
		NODE_WEIGHT_MUTATION_SCOPE:     0.01,
		NODE_BIAS_MUTATION_SCOPE:       0.01,

		CONNECTION_SPLIT_PROBABILITY: 0.0001,
		MUTATION_PROBABILITY:         0.5,

		NEW_CONNECTION_PROBABILITY: 0.0001,
	}
}
