package brain

// Connection
const CONNECTION_STRENGTH_MUTATE_PROBABILITY = 0.01
const CONNECTION_STRENGTH_MUTATION_SCOPE = 0.001

// Node
const NODE_WEIGHT_MUTATE_PROBABILITY = 0.05
const NODE_WEIGHT_MUTATION_SCOPE = 0.01
const NODE_BIAS_MUTATE_PROBABILITY = 0.01
const NODE_BIAS_MUTATION_SCOPE = 0.01

// Brain
const MUTATION_PROBABILITY = 0.5
const CONNECTION_SPLIT_PROBABILITY float64 = 0.0001
const NEW_CONNECTION_PROBABILITY = 0.0001
